name: Format Translation

permissions:
  contents: write

on:
  workflow_dispatch:


jobs:
  format-translation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

