# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "t2" ]
  pull_request:
    branches: [ "t2" ]

  # Allows you to run this workflow manually from the Actions tab

jobs:
  format-translation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: 🚀 Run format-translation script
        run: python .github/scripts/format-translation-script.py Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  
      - name: 📝 Commit changes 
        id: check_changes 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "format-translation-action"
          git add . 
          git diff-index --quiet HEAD || git commit -m "Format translation files"
          git push
